apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.1.3
      helm:
        releaseName: argocd
        valueFiles:
          - $values/charts/argocd/values.yaml
    - repoURL: https://github.com/sphiria/cluster
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: argocd-notifications-secret
      jsonPointers:
        - /data
        - /metadata/annotations/operator.1password.io~1item-version
