apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.vector.dev
      chart: vector
      targetRevision: 0.38.0
      helm:
        releaseName: vector
        valueFiles:
          - $values/charts/vector/values.yaml
    - repoURL: https://github.com/sphiria/cluster
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
